apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manager.yaml
images:
- name: controller
  newName: open-component-model/mpas-product-controller
  newTag: latest
- name: open-component-model/mpas-product-controller
  newName: ghcr.io/open-component-model/mpas-product-controller
  newTag: latest

# Uncomment to enable HTTPS for the registry
patches:
- path: ./patches/add_root_certificates.yaml
