apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: mpas-product-controller
    app.kubernetes.io/name: namespace
    app.kubernetes.io/instance: system
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: mpas-product-controller
    app.kubernetes.io/part-of: mpas-product-controller
    app.kubernetes.io/managed-by: kustomize
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mpas-product-controller
  namespace: system
  labels:
    app: mpas-product-controller
    app.kubernetes.io/name: deployment
    app.kubernetes.io/instance: mpas-product-controller
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: mpas-product-controller
    app.kubernetes.io/part-of: mpas-product-controller
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      app: mpas-product-controller
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app: mpas-product-controller
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - command:
        - /manager
        args:
        - --zap-log-level=4
        - --leader-elect
        - --oci-registry-addr=registry.ocm-system.svc.cluster.local:5000
        image: open-component-model/mpas-product-controller:latest
        name: manager
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      serviceAccountName: mpas-product-controller
      terminationGracePeriodSeconds: 10
