---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: mpas-product-controller-role
rules:
- apiGroups:
  - delivery.ocm.software
  resources:
  - componentsubscriptions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mpas.ocm.software
  resources:
  - productdeploymentgenerators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mpas.ocm.software
  resources:
  - productdeploymentgenerators/finalizers
  verbs:
  - update
- apiGroups:
  - mpas.ocm.software
  resources:
  - productdeploymentgenerators/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mpas.ocm.software
  resources:
  - productdeploymentpipelines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mpas.ocm.software
  resources:
  - productdeploymentpipelines/finalizers
  verbs:
  - update
- apiGroups:
  - mpas.ocm.software
  resources:
  - productdeploymentpipelines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mpas.ocm.software
  resources:
  - productdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mpas.ocm.software
  resources:
  - productdeployments/finalizers
  verbs:
  - update
- apiGroups:
  - mpas.ocm.software
  resources:
  - productdeployments/status
  verbs:
  - get
  - patch
  - update
