# permissions for end users to edit validations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: validation-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: mpas-product-controller
    app.kubernetes.io/part-of: mpas-product-controller
    app.kubernetes.io/managed-by: kustomize
  name: validation-editor-role
rules:
- apiGroups:
  - mpas.ocm.software
  resources:
  - validations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mpas.ocm.software
  resources:
  - validations/status
  verbs:
  - get
