apiVersion: mpas.ocm.software/v1alpha1
kind: Product
metadata:
  labels:
    app.kubernetes.io/name: product
    app.kubernetes.io/instance: product-sample
    app.kubernetes.io/part-of: mpas-product-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: mpas-product-controller
  name: product-sample
spec:
  # TODO(user): Add fields here
