apiVersion: mpas.ocm.software/v1alpha1
kind: Target
metadata:
  labels:
    app.kubernetes.io/name: target
    app.kubernetes.io/instance: target-sample
    app.kubernetes.io/part-of: mpas-product-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: mpas-product-controller
  name: target-sample
spec:
  type: Kubernetes
  access:
    secretRef:
      name: kube-config
