apiVersion: apps/v1
kind: Deployment
metadata:
  name: mpas-product-controller
  namespace: system
spec:
  template:
    spec:
      containers:
        - name: manager
          image: open-component-model/mpas-product-controller
          volumeMounts:
            - mountPath: "/etc/ssl/certs/registry-root.pem"
              subPath: "registry-root.pem"
              name: "certificates"
      volumes:
        - name: "certificates"
          secret:
            secretName: "ocm-registry-tls-certs"
            items:
              - key: "ca.crt"
                path: "registry-root.pem"
