# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/mpas.ocm.software_productdeploymentgenerators.yaml
- bases/mpas.ocm.software_productdeployments.yaml
- bases/mpas.ocm.software_productdeploymentpipelines.yaml
- bases/mpas.ocm.software_productdescriptions.yaml
- bases/mpas.ocm.software_targets.yaml
#+kubebuilder:scaffold:crdkustomizeresource

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
