---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: mpas-product-controller
    app.kubernetes.io/instance: mpas-product-controller-rolebinding
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/part-of: mpas-product-controller
  name: mpas-product-controller-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mpas-product-controller-role
subjects:
- kind: ServiceAccount
  name: mpas-product-controller
  namespace: mpas-system
